//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ITV {
    
    private ITVParam paramField;
    
    private ITVListeInterviews listeInterviewsField;
    
    /// <remarks/>
    public ITVParam Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
    
    /// <remarks/>
    public ITVListeInterviews ListeInterviews {
        get {
            return this.listeInterviewsField;
        }
        set {
            this.listeInterviewsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVParam {
    
    private System.DateTime pAR_ExportDateField;
    
    private bool pAR_ExportDateFieldSpecified;
    
    private ITVParamProject projectField;
    
    private ITVParamCountry countryField;
    
    /// <remarks/>
    public System.DateTime PAR_ExportDate {
        get {
            return this.pAR_ExportDateField;
        }
        set {
            this.pAR_ExportDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PAR_ExportDateSpecified {
        get {
            return this.pAR_ExportDateFieldSpecified;
        }
        set {
            this.pAR_ExportDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ITVParamProject Project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    public ITVParamCountry Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVParamProject {
    
    private string pRO_LanguageField;
    
    private string pRO_CodeField;
    
    /// <remarks/>
    public string PRO_Language {
        get {
            return this.pRO_LanguageField;
        }
        set {
            this.pRO_LanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PRO_Code {
        get {
            return this.pRO_CodeField;
        }
        set {
            this.pRO_CodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVParamCountry {
    
    private string cTY_codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CTY_code {
        get {
            return this.cTY_codeField;
        }
        set {
            this.cTY_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviews {
    
    private ITVListeInterviewsInterview interviewField;
    
    /// <remarks/>
    public ITVListeInterviewsInterview Interview {
        get {
            return this.interviewField;
        }
        set {
            this.interviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviewsInterview {
    
    private object iTV_IdField;
    
    private System.DateTime iTV_RecallDateField;
    
    private bool iTV_RecallDateFieldSpecified;
    
    private byte cTR_CodeField;
    
    private bool cTR_CodeFieldSpecified;
    
    private byte iTR_CodeField;
    
    private bool iTR_CodeFieldSpecified;
    
    private string iTR_CTY_CodeField;
    
    private byte iTR_CTR_CodeField;
    
    private bool iTR_CTR_CodeFieldSpecified;
    
    private string sBT_CodeField;
    
    private string sBT_NameField;
    
    private string sBT_FirstNameField;
    
    private byte sBT_SexField;
    
    private bool sBT_SexFieldSpecified;
    
    private System.DateTime sBT_BirthDateField;
    
    private bool sBT_BirthDateFieldSpecified;
    
    private System.DateTime iTG_ReleaseField;
    
    private bool iTG_ReleaseFieldSpecified;
    
    private byte iTG_NumField;
    
    private bool iTG_NumFieldSpecified;
    
    private System.DateTime iTG_DateField;
    
    private bool iTG_DateFieldSpecified;
    
    private byte iTG_SubjectHeightField;
    
    private bool iTG_SubjectHeightFieldSpecified;
    
    private byte iTG_SubjectWeightField;
    
    private bool iTG_SubjectWeightFieldSpecified;
    
    private string iTG_VURecallField;
    
    private string iTG_VUNextRecallField;
    
    private decimal iTG_EnergyRequirementField;
    
    private bool iTG_EnergyRequirementFieldSpecified;
    
    private byte iTG_EnergyCalculatedField;
    
    private bool iTG_EnergyCalculatedFieldSpecified;
    
    private System.DateTime iTG_TimeGIField;
    
    private bool iTG_TimeGIFieldSpecified;
    
    private System.DateTime iTG_TimeQLField;
    
    private bool iTG_TimeQLFieldSpecified;
    
    private System.DateTime iTG_TimeDQField;
    
    private bool iTG_TimeDQFieldSpecified;
    
    private System.DateTime iTG_TimeDSField;
    
    private bool iTG_TimeDSFieldSpecified;
    
    private System.DateTime iTG_TimeALLField;
    
    private bool iTG_TimeALLFieldSpecified;
    
    private System.DateTime iTG_RecomputeDateField;
    
    private bool iTG_RecomputeDateFieldSpecified;
    
    private byte iTG_SPD_codeField;
    
    private bool iTG_SPD_codeFieldSpecified;
    
    private byte iTG_SPT_codeField;
    
    private bool iTG_SPT_codeFieldSpecified;
    
    private byte iTG_VersionField;
    
    private bool iTG_VersionFieldSpecified;
    
    private object listeNotesField;
    
    private ITVListeInterviewsInterviewLigneITV[] listeLignesITVField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public object ITV_Id {
        get {
            return this.iTV_IdField;
        }
        set {
            this.iTV_IdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ITV_RecallDate {
        get {
            return this.iTV_RecallDateField;
        }
        set {
            this.iTV_RecallDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITV_RecallDateSpecified {
        get {
            return this.iTV_RecallDateFieldSpecified;
        }
        set {
            this.iTV_RecallDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte CTR_Code {
        get {
            return this.cTR_CodeField;
        }
        set {
            this.cTR_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CTR_CodeSpecified {
        get {
            return this.cTR_CodeFieldSpecified;
        }
        set {
            this.cTR_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITR_Code {
        get {
            return this.iTR_CodeField;
        }
        set {
            this.iTR_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITR_CodeSpecified {
        get {
            return this.iTR_CodeFieldSpecified;
        }
        set {
            this.iTR_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ITR_CTY_Code {
        get {
            return this.iTR_CTY_CodeField;
        }
        set {
            this.iTR_CTY_CodeField = value;
        }
    }
    
    /// <remarks/>
    public byte ITR_CTR_Code {
        get {
            return this.iTR_CTR_CodeField;
        }
        set {
            this.iTR_CTR_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITR_CTR_CodeSpecified {
        get {
            return this.iTR_CTR_CodeFieldSpecified;
        }
        set {
            this.iTR_CTR_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string SBT_Code {
        get {
            return this.sBT_CodeField;
        }
        set {
            this.sBT_CodeField = value;
        }
    }
    
    /// <remarks/>
    public string SBT_Name {
        get {
            return this.sBT_NameField;
        }
        set {
            this.sBT_NameField = value;
        }
    }
    
    /// <remarks/>
    public string SBT_FirstName {
        get {
            return this.sBT_FirstNameField;
        }
        set {
            this.sBT_FirstNameField = value;
        }
    }
    
    /// <remarks/>
    public byte SBT_Sex {
        get {
            return this.sBT_SexField;
        }
        set {
            this.sBT_SexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SBT_SexSpecified {
        get {
            return this.sBT_SexFieldSpecified;
        }
        set {
            this.sBT_SexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SBT_BirthDate {
        get {
            return this.sBT_BirthDateField;
        }
        set {
            this.sBT_BirthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SBT_BirthDateSpecified {
        get {
            return this.sBT_BirthDateFieldSpecified;
        }
        set {
            this.sBT_BirthDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ITG_Release {
        get {
            return this.iTG_ReleaseField;
        }
        set {
            this.iTG_ReleaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_ReleaseSpecified {
        get {
            return this.iTG_ReleaseFieldSpecified;
        }
        set {
            this.iTG_ReleaseFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_Num {
        get {
            return this.iTG_NumField;
        }
        set {
            this.iTG_NumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_NumSpecified {
        get {
            return this.iTG_NumFieldSpecified;
        }
        set {
            this.iTG_NumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ITG_Date {
        get {
            return this.iTG_DateField;
        }
        set {
            this.iTG_DateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_DateSpecified {
        get {
            return this.iTG_DateFieldSpecified;
        }
        set {
            this.iTG_DateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_SubjectHeight {
        get {
            return this.iTG_SubjectHeightField;
        }
        set {
            this.iTG_SubjectHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_SubjectHeightSpecified {
        get {
            return this.iTG_SubjectHeightFieldSpecified;
        }
        set {
            this.iTG_SubjectHeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_SubjectWeight {
        get {
            return this.iTG_SubjectWeightField;
        }
        set {
            this.iTG_SubjectWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_SubjectWeightSpecified {
        get {
            return this.iTG_SubjectWeightFieldSpecified;
        }
        set {
            this.iTG_SubjectWeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ITG_VURecall {
        get {
            return this.iTG_VURecallField;
        }
        set {
            this.iTG_VURecallField = value;
        }
    }
    
    /// <remarks/>
    public string ITG_VUNextRecall {
        get {
            return this.iTG_VUNextRecallField;
        }
        set {
            this.iTG_VUNextRecallField = value;
        }
    }
    
    /// <remarks/>
    public decimal ITG_EnergyRequirement {
        get {
            return this.iTG_EnergyRequirementField;
        }
        set {
            this.iTG_EnergyRequirementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_EnergyRequirementSpecified {
        get {
            return this.iTG_EnergyRequirementFieldSpecified;
        }
        set {
            this.iTG_EnergyRequirementFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_EnergyCalculated {
        get {
            return this.iTG_EnergyCalculatedField;
        }
        set {
            this.iTG_EnergyCalculatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_EnergyCalculatedSpecified {
        get {
            return this.iTG_EnergyCalculatedFieldSpecified;
        }
        set {
            this.iTG_EnergyCalculatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ITG_TimeGI {
        get {
            return this.iTG_TimeGIField;
        }
        set {
            this.iTG_TimeGIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_TimeGISpecified {
        get {
            return this.iTG_TimeGIFieldSpecified;
        }
        set {
            this.iTG_TimeGIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ITG_TimeQL {
        get {
            return this.iTG_TimeQLField;
        }
        set {
            this.iTG_TimeQLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_TimeQLSpecified {
        get {
            return this.iTG_TimeQLFieldSpecified;
        }
        set {
            this.iTG_TimeQLFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ITG_TimeDQ {
        get {
            return this.iTG_TimeDQField;
        }
        set {
            this.iTG_TimeDQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_TimeDQSpecified {
        get {
            return this.iTG_TimeDQFieldSpecified;
        }
        set {
            this.iTG_TimeDQFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ITG_TimeDS {
        get {
            return this.iTG_TimeDSField;
        }
        set {
            this.iTG_TimeDSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_TimeDSSpecified {
        get {
            return this.iTG_TimeDSFieldSpecified;
        }
        set {
            this.iTG_TimeDSFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime ITG_TimeALL {
        get {
            return this.iTG_TimeALLField;
        }
        set {
            this.iTG_TimeALLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_TimeALLSpecified {
        get {
            return this.iTG_TimeALLFieldSpecified;
        }
        set {
            this.iTG_TimeALLFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ITG_RecomputeDate {
        get {
            return this.iTG_RecomputeDateField;
        }
        set {
            this.iTG_RecomputeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_RecomputeDateSpecified {
        get {
            return this.iTG_RecomputeDateFieldSpecified;
        }
        set {
            this.iTG_RecomputeDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_SPD_code {
        get {
            return this.iTG_SPD_codeField;
        }
        set {
            this.iTG_SPD_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_SPD_codeSpecified {
        get {
            return this.iTG_SPD_codeFieldSpecified;
        }
        set {
            this.iTG_SPD_codeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_SPT_code {
        get {
            return this.iTG_SPT_codeField;
        }
        set {
            this.iTG_SPT_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_SPT_codeSpecified {
        get {
            return this.iTG_SPT_codeFieldSpecified;
        }
        set {
            this.iTG_SPT_codeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITG_Version {
        get {
            return this.iTG_VersionField;
        }
        set {
            this.iTG_VersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITG_VersionSpecified {
        get {
            return this.iTG_VersionFieldSpecified;
        }
        set {
            this.iTG_VersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public object ListeNotes {
        get {
            return this.listeNotesField;
        }
        set {
            this.listeNotesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LigneITV", IsNullable=false)]
    public ITVListeInterviewsInterviewLigneITV[] ListeLignesITV {
        get {
            return this.listeLignesITVField;
        }
        set {
            this.listeLignesITVField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviewsInterviewLigneITV {
    
    private byte iTL_POC_CodeField;
    
    private bool iTL_POC_CodeFieldSpecified;
    
    private byte iTL_FCO_CodeField;
    
    private bool iTL_FCO_CodeFieldSpecified;
    
    private ushort iTL_FCOHourField;
    
    private bool iTL_FCOHourFieldSpecified;
    
    private byte iTL_TOKField;
    
    private bool iTL_TOKFieldSpecified;
    
    private byte iTL_QLINUMField;
    
    private bool iTL_QLINUMFieldSpecified;
    
    private byte iTL_ING_NUMField;
    
    private bool iTL_ING_NUMFieldSpecified;
    
    private byte iTL_S_ING_NUMField;
    
    private bool iTL_S_ING_NUMFieldSpecified;
    
    private byte iTL_TypeField;
    
    private bool iTL_TypeFieldSpecified;
    
    private ushort iTL_FoodNumField;
    
    private bool iTL_FoodNumFieldSpecified;
    
    private byte iTL_GroupField;
    
    private bool iTL_GroupFieldSpecified;
    
    private byte iTL_SubGroup1Field;
    
    private bool iTL_SubGroup1FieldSpecified;
    
    private string iTL_SubGroup2Field;
    
    private object iTL_DS_ClassifField;
    
    private string iTL_F_TypeField;
    
    private string iTL_I_TypeField;
    
    private byte iTL_R_ModifField;
    
    private bool iTL_R_ModifFieldSpecified;
    
    private byte iTL_I_ModifField;
    
    private bool iTL_I_ModifFieldSpecified;
    
    private string iTL_R_TypeField;
    
    private string iTL_TextField;
    
    private string iTL_NameField;
    
    private string iTL_Facets_STRField;
    
    private object iTL_BrandNameField;
    
    private byte iTL_StatusField;
    
    private bool iTL_StatusFieldSpecified;
    
    private ushort iTL_Estim_QTYField;
    
    private bool iTL_Estim_QTYFieldSpecified;
    
    private string iTL_Q_MethodField;
    
    private string iTL_QM_CodeField;
    
    private string iTL_QUNITField;
    
    private ushort iTL_NGRAMSField;
    
    private bool iTL_NGRAMSFieldSpecified;
    
    private byte iTL_ProportField;
    
    private bool iTL_ProportFieldSpecified;
    
    private byte iTL_HHMFractField;
    
    private bool iTL_HHMFractFieldSpecified;
    
    private byte iTL_R_FractField;
    
    private bool iTL_R_FractFieldSpecified;
    
    private byte iTL_RawCookedField;
    
    private bool iTL_RawCookedFieldSpecified;
    
    private byte iTL_ConsRawCoField;
    
    private bool iTL_ConsRawCoFieldSpecified;
    
    private decimal iTL_ConverField;
    
    private bool iTL_ConverFieldSpecified;
    
    private byte iTL_EDIBField;
    
    private bool iTL_EDIBFieldSpecified;
    
    private decimal iTL_EDIB_CSTEField;
    
    private bool iTL_EDIB_CSTEFieldSpecified;
    
    private byte iTL_DENSITYField;
    
    private bool iTL_DENSITYFieldSpecified;
    
    private bool iTL_FATLEFTOField;
    
    private bool iTL_FATLEFTOFieldSpecified;
    
    private byte iTL_FAT_PCTField;
    
    private bool iTL_FAT_PCTFieldSpecified;
    
    private decimal iTL_PCT_CONSField;
    
    private bool iTL_PCT_CONSFieldSpecified;
    
    private decimal iTL_PCT_ESTIMField;
    
    private bool iTL_PCT_ESTIMFieldSpecified;
    
    private decimal iTL_CONS_QTYField;
    
    private bool iTL_CONS_QTYFieldSpecified;
    
    private decimal iTL_R_COOKEDField;
    
    private bool iTL_R_COOKEDFieldSpecified;
    
    private decimal iTL_R_EDIBField;
    
    private bool iTL_R_EDIBFieldSpecified;
    
    private decimal iTL_RAW_QField;
    
    private bool iTL_RAW_QFieldSpecified;
    
    private decimal iTL_RAW_Q_WField;
    
    private bool iTL_RAW_Q_WFieldSpecified;
    
    private byte iTL_MAXField;
    
    private bool iTL_MAXFieldSpecified;
    
    private bool iTL_SUPPLField;
    
    private bool iTL_SUPPLFieldSpecified;
    
    private ushort iTL_ITEM_SEQField;
    
    private bool iTL_ITEM_SEQFieldSpecified;
    
    private ITVListeInterviewsInterviewLigneITVListeITV_Quantity listeITV_QuantityField;
    
    private ITVListeInterviewsInterviewLigneITVITV_Nutriment[] listeITV_NutrimentsField;
    
    private object listeNotesField;
    
    /// <remarks/>
    public byte ITL_POC_Code {
        get {
            return this.iTL_POC_CodeField;
        }
        set {
            this.iTL_POC_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_POC_CodeSpecified {
        get {
            return this.iTL_POC_CodeFieldSpecified;
        }
        set {
            this.iTL_POC_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_FCO_Code {
        get {
            return this.iTL_FCO_CodeField;
        }
        set {
            this.iTL_FCO_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_FCO_CodeSpecified {
        get {
            return this.iTL_FCO_CodeFieldSpecified;
        }
        set {
            this.iTL_FCO_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort ITL_FCOHour {
        get {
            return this.iTL_FCOHourField;
        }
        set {
            this.iTL_FCOHourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_FCOHourSpecified {
        get {
            return this.iTL_FCOHourFieldSpecified;
        }
        set {
            this.iTL_FCOHourFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_TOK {
        get {
            return this.iTL_TOKField;
        }
        set {
            this.iTL_TOKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_TOKSpecified {
        get {
            return this.iTL_TOKFieldSpecified;
        }
        set {
            this.iTL_TOKFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_QLINUM {
        get {
            return this.iTL_QLINUMField;
        }
        set {
            this.iTL_QLINUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_QLINUMSpecified {
        get {
            return this.iTL_QLINUMFieldSpecified;
        }
        set {
            this.iTL_QLINUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_ING_NUM {
        get {
            return this.iTL_ING_NUMField;
        }
        set {
            this.iTL_ING_NUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_ING_NUMSpecified {
        get {
            return this.iTL_ING_NUMFieldSpecified;
        }
        set {
            this.iTL_ING_NUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_S_ING_NUM {
        get {
            return this.iTL_S_ING_NUMField;
        }
        set {
            this.iTL_S_ING_NUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_S_ING_NUMSpecified {
        get {
            return this.iTL_S_ING_NUMFieldSpecified;
        }
        set {
            this.iTL_S_ING_NUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_Type {
        get {
            return this.iTL_TypeField;
        }
        set {
            this.iTL_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_TypeSpecified {
        get {
            return this.iTL_TypeFieldSpecified;
        }
        set {
            this.iTL_TypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort ITL_FoodNum {
        get {
            return this.iTL_FoodNumField;
        }
        set {
            this.iTL_FoodNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_FoodNumSpecified {
        get {
            return this.iTL_FoodNumFieldSpecified;
        }
        set {
            this.iTL_FoodNumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_Group {
        get {
            return this.iTL_GroupField;
        }
        set {
            this.iTL_GroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_GroupSpecified {
        get {
            return this.iTL_GroupFieldSpecified;
        }
        set {
            this.iTL_GroupFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_SubGroup1 {
        get {
            return this.iTL_SubGroup1Field;
        }
        set {
            this.iTL_SubGroup1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_SubGroup1Specified {
        get {
            return this.iTL_SubGroup1FieldSpecified;
        }
        set {
            this.iTL_SubGroup1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ITL_SubGroup2 {
        get {
            return this.iTL_SubGroup2Field;
        }
        set {
            this.iTL_SubGroup2Field = value;
        }
    }
    
    /// <remarks/>
    public object ITL_DS_Classif {
        get {
            return this.iTL_DS_ClassifField;
        }
        set {
            this.iTL_DS_ClassifField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_F_Type {
        get {
            return this.iTL_F_TypeField;
        }
        set {
            this.iTL_F_TypeField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_I_Type {
        get {
            return this.iTL_I_TypeField;
        }
        set {
            this.iTL_I_TypeField = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_R_Modif {
        get {
            return this.iTL_R_ModifField;
        }
        set {
            this.iTL_R_ModifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_R_ModifSpecified {
        get {
            return this.iTL_R_ModifFieldSpecified;
        }
        set {
            this.iTL_R_ModifFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_I_Modif {
        get {
            return this.iTL_I_ModifField;
        }
        set {
            this.iTL_I_ModifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_I_ModifSpecified {
        get {
            return this.iTL_I_ModifFieldSpecified;
        }
        set {
            this.iTL_I_ModifFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ITL_R_Type {
        get {
            return this.iTL_R_TypeField;
        }
        set {
            this.iTL_R_TypeField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_Text {
        get {
            return this.iTL_TextField;
        }
        set {
            this.iTL_TextField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_Name {
        get {
            return this.iTL_NameField;
        }
        set {
            this.iTL_NameField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_Facets_STR {
        get {
            return this.iTL_Facets_STRField;
        }
        set {
            this.iTL_Facets_STRField = value;
        }
    }
    
    /// <remarks/>
    public object ITL_BrandName {
        get {
            return this.iTL_BrandNameField;
        }
        set {
            this.iTL_BrandNameField = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_Status {
        get {
            return this.iTL_StatusField;
        }
        set {
            this.iTL_StatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_StatusSpecified {
        get {
            return this.iTL_StatusFieldSpecified;
        }
        set {
            this.iTL_StatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort ITL_Estim_QTY {
        get {
            return this.iTL_Estim_QTYField;
        }
        set {
            this.iTL_Estim_QTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_Estim_QTYSpecified {
        get {
            return this.iTL_Estim_QTYFieldSpecified;
        }
        set {
            this.iTL_Estim_QTYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ITL_Q_Method {
        get {
            return this.iTL_Q_MethodField;
        }
        set {
            this.iTL_Q_MethodField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_QM_Code {
        get {
            return this.iTL_QM_CodeField;
        }
        set {
            this.iTL_QM_CodeField = value;
        }
    }
    
    /// <remarks/>
    public string ITL_QUNIT {
        get {
            return this.iTL_QUNITField;
        }
        set {
            this.iTL_QUNITField = value;
        }
    }
    
    /// <remarks/>
    public ushort ITL_NGRAMS {
        get {
            return this.iTL_NGRAMSField;
        }
        set {
            this.iTL_NGRAMSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_NGRAMSSpecified {
        get {
            return this.iTL_NGRAMSFieldSpecified;
        }
        set {
            this.iTL_NGRAMSFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_Proport {
        get {
            return this.iTL_ProportField;
        }
        set {
            this.iTL_ProportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_ProportSpecified {
        get {
            return this.iTL_ProportFieldSpecified;
        }
        set {
            this.iTL_ProportFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_HHMFract {
        get {
            return this.iTL_HHMFractField;
        }
        set {
            this.iTL_HHMFractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_HHMFractSpecified {
        get {
            return this.iTL_HHMFractFieldSpecified;
        }
        set {
            this.iTL_HHMFractFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_R_Fract {
        get {
            return this.iTL_R_FractField;
        }
        set {
            this.iTL_R_FractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_R_FractSpecified {
        get {
            return this.iTL_R_FractFieldSpecified;
        }
        set {
            this.iTL_R_FractFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_RawCooked {
        get {
            return this.iTL_RawCookedField;
        }
        set {
            this.iTL_RawCookedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_RawCookedSpecified {
        get {
            return this.iTL_RawCookedFieldSpecified;
        }
        set {
            this.iTL_RawCookedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_ConsRawCo {
        get {
            return this.iTL_ConsRawCoField;
        }
        set {
            this.iTL_ConsRawCoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_ConsRawCoSpecified {
        get {
            return this.iTL_ConsRawCoFieldSpecified;
        }
        set {
            this.iTL_ConsRawCoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_Conver {
        get {
            return this.iTL_ConverField;
        }
        set {
            this.iTL_ConverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_ConverSpecified {
        get {
            return this.iTL_ConverFieldSpecified;
        }
        set {
            this.iTL_ConverFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_EDIB {
        get {
            return this.iTL_EDIBField;
        }
        set {
            this.iTL_EDIBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_EDIBSpecified {
        get {
            return this.iTL_EDIBFieldSpecified;
        }
        set {
            this.iTL_EDIBFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_EDIB_CSTE {
        get {
            return this.iTL_EDIB_CSTEField;
        }
        set {
            this.iTL_EDIB_CSTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_EDIB_CSTESpecified {
        get {
            return this.iTL_EDIB_CSTEFieldSpecified;
        }
        set {
            this.iTL_EDIB_CSTEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_DENSITY {
        get {
            return this.iTL_DENSITYField;
        }
        set {
            this.iTL_DENSITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_DENSITYSpecified {
        get {
            return this.iTL_DENSITYFieldSpecified;
        }
        set {
            this.iTL_DENSITYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ITL_FATLEFTO {
        get {
            return this.iTL_FATLEFTOField;
        }
        set {
            this.iTL_FATLEFTOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_FATLEFTOSpecified {
        get {
            return this.iTL_FATLEFTOFieldSpecified;
        }
        set {
            this.iTL_FATLEFTOFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_FAT_PCT {
        get {
            return this.iTL_FAT_PCTField;
        }
        set {
            this.iTL_FAT_PCTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_FAT_PCTSpecified {
        get {
            return this.iTL_FAT_PCTFieldSpecified;
        }
        set {
            this.iTL_FAT_PCTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_PCT_CONS {
        get {
            return this.iTL_PCT_CONSField;
        }
        set {
            this.iTL_PCT_CONSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_PCT_CONSSpecified {
        get {
            return this.iTL_PCT_CONSFieldSpecified;
        }
        set {
            this.iTL_PCT_CONSFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_PCT_ESTIM {
        get {
            return this.iTL_PCT_ESTIMField;
        }
        set {
            this.iTL_PCT_ESTIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_PCT_ESTIMSpecified {
        get {
            return this.iTL_PCT_ESTIMFieldSpecified;
        }
        set {
            this.iTL_PCT_ESTIMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_CONS_QTY {
        get {
            return this.iTL_CONS_QTYField;
        }
        set {
            this.iTL_CONS_QTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_CONS_QTYSpecified {
        get {
            return this.iTL_CONS_QTYFieldSpecified;
        }
        set {
            this.iTL_CONS_QTYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_R_COOKED {
        get {
            return this.iTL_R_COOKEDField;
        }
        set {
            this.iTL_R_COOKEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_R_COOKEDSpecified {
        get {
            return this.iTL_R_COOKEDFieldSpecified;
        }
        set {
            this.iTL_R_COOKEDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_R_EDIB {
        get {
            return this.iTL_R_EDIBField;
        }
        set {
            this.iTL_R_EDIBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_R_EDIBSpecified {
        get {
            return this.iTL_R_EDIBFieldSpecified;
        }
        set {
            this.iTL_R_EDIBFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_RAW_Q {
        get {
            return this.iTL_RAW_QField;
        }
        set {
            this.iTL_RAW_QField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_RAW_QSpecified {
        get {
            return this.iTL_RAW_QFieldSpecified;
        }
        set {
            this.iTL_RAW_QFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITL_RAW_Q_W {
        get {
            return this.iTL_RAW_Q_WField;
        }
        set {
            this.iTL_RAW_Q_WField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_RAW_Q_WSpecified {
        get {
            return this.iTL_RAW_Q_WFieldSpecified;
        }
        set {
            this.iTL_RAW_Q_WFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITL_MAX {
        get {
            return this.iTL_MAXField;
        }
        set {
            this.iTL_MAXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_MAXSpecified {
        get {
            return this.iTL_MAXFieldSpecified;
        }
        set {
            this.iTL_MAXFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool ITL_SUPPL {
        get {
            return this.iTL_SUPPLField;
        }
        set {
            this.iTL_SUPPLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_SUPPLSpecified {
        get {
            return this.iTL_SUPPLFieldSpecified;
        }
        set {
            this.iTL_SUPPLFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort ITL_ITEM_SEQ {
        get {
            return this.iTL_ITEM_SEQField;
        }
        set {
            this.iTL_ITEM_SEQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITL_ITEM_SEQSpecified {
        get {
            return this.iTL_ITEM_SEQFieldSpecified;
        }
        set {
            this.iTL_ITEM_SEQFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ITVListeInterviewsInterviewLigneITVListeITV_Quantity ListeITV_Quantity {
        get {
            return this.listeITV_QuantityField;
        }
        set {
            this.listeITV_QuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ITV_Nutriment", IsNullable=false)]
    public ITVListeInterviewsInterviewLigneITVITV_Nutriment[] ListeITV_Nutriments {
        get {
            return this.listeITV_NutrimentsField;
        }
        set {
            this.listeITV_NutrimentsField = value;
        }
    }
    
    /// <remarks/>
    public object ListeNotes {
        get {
            return this.listeNotesField;
        }
        set {
            this.listeNotesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviewsInterviewLigneITVListeITV_Quantity {
    
    private ITVListeInterviewsInterviewLigneITVListeITV_QuantityITV_Quantity_Service iTV_Quantity_ServiceField;
    
    /// <remarks/>
    public ITVListeInterviewsInterviewLigneITVListeITV_QuantityITV_Quantity_Service ITV_Quantity_Service {
        get {
            return this.iTV_Quantity_ServiceField;
        }
        set {
            this.iTV_Quantity_ServiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviewsInterviewLigneITVListeITV_QuantityITV_Quantity_Service {
    
    private byte iTQ_OrderField;
    
    private bool iTQ_OrderFieldSpecified;
    
    private byte iTQ_SH_SurfaceField;
    
    private bool iTQ_SH_SurfaceFieldSpecified;
    
    private byte iTQ_TH_ThickField;
    
    private bool iTQ_TH_ThickFieldSpecified;
    
    private byte iTQ_PH_CodeField;
    
    private bool iTQ_PH_CodeFieldSpecified;
    
    private byte iTQ_PH_QTYField;
    
    private bool iTQ_PH_QTYFieldSpecified;
    
    private byte iTQ_FRACTField;
    
    private bool iTQ_FRACTFieldSpecified;
    
    /// <remarks/>
    public byte ITQ_Order {
        get {
            return this.iTQ_OrderField;
        }
        set {
            this.iTQ_OrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_OrderSpecified {
        get {
            return this.iTQ_OrderFieldSpecified;
        }
        set {
            this.iTQ_OrderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITQ_SH_Surface {
        get {
            return this.iTQ_SH_SurfaceField;
        }
        set {
            this.iTQ_SH_SurfaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_SH_SurfaceSpecified {
        get {
            return this.iTQ_SH_SurfaceFieldSpecified;
        }
        set {
            this.iTQ_SH_SurfaceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITQ_TH_Thick {
        get {
            return this.iTQ_TH_ThickField;
        }
        set {
            this.iTQ_TH_ThickField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_TH_ThickSpecified {
        get {
            return this.iTQ_TH_ThickFieldSpecified;
        }
        set {
            this.iTQ_TH_ThickFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITQ_PH_Code {
        get {
            return this.iTQ_PH_CodeField;
        }
        set {
            this.iTQ_PH_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_PH_CodeSpecified {
        get {
            return this.iTQ_PH_CodeFieldSpecified;
        }
        set {
            this.iTQ_PH_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITQ_PH_QTY {
        get {
            return this.iTQ_PH_QTYField;
        }
        set {
            this.iTQ_PH_QTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_PH_QTYSpecified {
        get {
            return this.iTQ_PH_QTYFieldSpecified;
        }
        set {
            this.iTQ_PH_QTYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ITQ_FRACT {
        get {
            return this.iTQ_FRACTField;
        }
        set {
            this.iTQ_FRACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITQ_FRACTSpecified {
        get {
            return this.iTQ_FRACTFieldSpecified;
        }
        set {
            this.iTQ_FRACTFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITVListeInterviewsInterviewLigneITVITV_Nutriment {
    
    private byte nTR_CodeField;
    
    private bool nTR_CodeFieldSpecified;
    
    private decimal iTV_NTR_ValueField;
    
    private bool iTV_NTR_ValueFieldSpecified;
    
    /// <remarks/>
    public byte NTR_Code {
        get {
            return this.nTR_CodeField;
        }
        set {
            this.nTR_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NTR_CodeSpecified {
        get {
            return this.nTR_CodeFieldSpecified;
        }
        set {
            this.nTR_CodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ITV_NTR_Value {
        get {
            return this.iTV_NTR_ValueField;
        }
        set {
            this.iTV_NTR_ValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ITV_NTR_ValueSpecified {
        get {
            return this.iTV_NTR_ValueFieldSpecified;
        }
        set {
            this.iTV_NTR_ValueFieldSpecified = value;
        }
    }
}
